trigger:
  branches:
    include:
      - main  # Adjust this to match your main branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true  # Ensure credentials are persisted for fetching code from GitHub

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@1
  displayName: 'Terraform Init'
  inputs:
    command: 'init'

- task: TerraformCLI@1
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    commandOptions: '-out=tfplan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'  # Use the default working directory

- task: TerraformCLI@1
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    commandOptions: 'tfplan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'  # Use the default working directory
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

