trigger:
  branches:
    include:
      - main  # Adjust this to match your main branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true  # Ensure credentials are persisted for fetching code from GitHub

- script: |
    wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt update
    sudo apt install terraform
  displayName: 'Install Terraform'

- script: |
    terraform init
    terraform plan -var "resource_group_name=my-resrsilicongroup" -var "location=East US" -out=tfplan
  displayName: 'Terraform Init and Plan'

- script: |
    terraform apply tfplan
  displayName: 'Terraform Apply'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

